### ISSUE TITLE
Strukturierung Repository

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#2]
- Es wäre vielleicht sinnvoll sich auf eine Struktur bei der Beschreibung der Commits zu einigen und vielleicht doppelte Commit Beschreibungen zu vermeiden

> Ich wäre dafür die Commits auf Deutsch zu beschreiben, weil wir ja auch auf Deutsch dokumentieren.

- Was hat es mit dem Submodule 47c74004187da63581d9457409c28e621a569ec5 auf sich? Hat das irgendeinen Hintergrund oder ist das aus Versehen passiert?

> Als kleiner Hinweis vielleicht immer drauf achten vor jedem `git push` immer ein `git pull` auszuführen, damit man keine unnötigen Merges verursacht.

**Comment by MaxHaufe** [comment]
Zu Punkt 1:
- Ich denke wir sollten die Commits auch auf Deutsch schreiben in der Form `Issue #n xyz hinzugefügt`, wobei "xyz hinzugefügt" hier nur ein Platzhalter ist.
- Ich weiß auch nur spontan nicht, ob wir das schon besprochen haben, aber ich wäre dafür, pro Commit nur ein Issue zu bearbeiten - wegen der Übersichtlichkeit.
