### ISSUE TITLE
Datenbankmodell anfangen

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#28]

**Comment by Lernni** [comment]
Bei der Tabelle Flugsession muss es eine SessionID als PK geben, statt nur die PilotenID. Ein Pilot kann ja mehrere Sessions haben. Die Beziehung zwischen Pilot/Flugsession wäre ja dann 1 zu mc.

**Comment by MaxHaufe** [comment]
Stimmt, soll der PK dann nur die SessionID sein, also für jeden Piloten gibt es Flugsession 1..n oder soll der PK sich aus SessionID und PilotenID zusammensetzen, sodass z.b. Hans die SessionID 0, Clara die SessionID 1, Hans die SessionID 2, [...] hat?

**Comment by Lernni** [comment]
Ich würde nur SessionID als PK machen.
