### ISSUE TITLE
Projektname in den AsciiDoc Dokumenten

### ISSUE THREAD

**Issue by tigion** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#3]
In der Datei *docs/_includes/default-attributes.inc.adoc* kann im Attribut **:project-name:** der Projektname gesetzt werden, aber bitte ohne die Platzhaltersymbole `<>` und `{}`. Dieser wird dann automatisch in allen Dokumenten beim Generieren entsprechend ersetzt:

Bspw.:
```
:project-name: Anwesenheitserfassung für Modellflugplatz (E2)
```

**Comment by simonherbstrith** [comment]
:project-name: Anwesenheitserfassung der Piloten auf dem Vereinsflugplatz des Mfc-Rossendorf (E2)
