### ISSUE TITLE
Wireframes weiterentwickeln

### ISSUE THREAD

**Issue by alexanderheiss99** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#45]

**Comment by MaxHaufe** [comment]
Wir haben UC04 von Pilotendaten löschen zu Piloten deaktivieren umbenannt.

Demnach brauchen wir in der Mitgliederübersicht.png keinen "löschen" Knopf mehr, sondern "Deaktivieren".

Ich denke nicht, dass du das nochmal ändern musst, aber ich lass mal hier so stehen, falls du irgendwann noch mal was an dem Wireframe machst.

**Comment by MaxHaufe** [comment]
Außerdem habe ich einen neuen UC erstellt, UC11 - Piloten reaktivieren, commit: 6e95f128ba079810a8eb2d54efa8d47b9b565228

Das heißt, für den Fall, dass in Zukunft nochmal jemand vor hat, in einem Wireframe einen deaktivierten Piloten darzustellen, müsste dann neben diesem ein **Reaktivieren** statt **Deaktivieren** Button sein.
