### ISSUE TITLE
Begriffe vereinheitlichen

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#51]
Die Begriffe in den Use-Cases müssen vereinheitlicht werden und gegebenenfalls im Glossar ergänzt werden. Vor allem ist wichtig, dass "Vereinsmitglied" durch "Pilot" ersetzt wird, da nicht jedes Vereinsmitglied ein Pilot ist, wir das aber bisher so beschrieben haben.

**Comment by Tsatsra** [comment]
Alle Use Cases wurden überarbeitet.
