### ISSUE TITLE
Datenschutz

### ISSUE THREAD

**Issue by ghost** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#61]
Genaue Anforderungen an den Datenschutz formulieren, Frist nach der deaktivierte Piloten und Flugprotokoll automatisch gelöscht werden, evtl. Auskunft für Nutzer über ihre personenbezogenen Daten

**Comment by Lernni** [comment]
- Informationen zum Datenschutz dokumentieren in den systemweiten Anforderungen
