### ISSUE TITLE
Dokumentation korrigieren

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#62]
## Kommentare von Prof. Anke abarbeiten
- ausgenommen: Architektur-Notebook, Design
- zu Benutzerumgebung (1.3.2):
   - Analyse von Einsatzbedingungen für das System -> Beschreibung wie dort gearbeitet wird
   - Wer hat welche Aufgaben im Verein?
   - Welche Handlungsabläufe vor Ort?
   - Welche Probleme treten auf?
   - Welches System ist derzeit im Einsatz?
   - Wer hat welche Rechte und Pflichten?
- zu Zusätzliche Produktanforderungen (1.5):
   - System muss datenschutzkonform sein -> neue Anforderung
   - "Moderne Gestaltung der Weboberfläche..." -> Fokus auf Gestaltung: Weboberfläche soll "zeitgemäß" sein
- zu Use-Case UC01 (2.2):
   - Wir haben die Fehlerfälle ja extra herausgenommen, da sie über unseren Systemrahmen hinausgehen. Nicht sicher, welche Fehlerfälle sonst gemeint sein könnten...
- zu Use-Case UC08 (2.9.5):
   - Sein Kommentar entfällt komplett, da wir jetzt eh ereignisgesteuert arbeiten
- Bedienungsanleitung an die entsprechenden Use-Cases aufteilen
## Änderungen vom letzten Kundenmeeting aufnehmen
- Wechsel von Angular zu Vue
- Wechsel von zeitgesteuerter Synchronisation zu ereignisgesteuerter Synchronisation
- Use-Case UC10: Gastflüge
## Neuer Punkt: Deployment hinzufügen
- Protokoll vom 17.04. anpassen
- Ordner `deployment` in den docs nutzen

**Comment by JakobLaufer** [comment]
**Vision**
• Alle Kleinigkeiten & Formulierungen ausgebessert
• Neue Anforderung hinzugefügt: System muss Dateschutzkomform sein
• Fokus auf Gestaltung etc...
• Benutzerumgebung neu überarbeitet
**Use-Case_Modell**
• Subsystem in Package geändert (übersichtlicher) 
• "Zeitsteuerung" als zusätzlicher Akteur (Auch im UC6 & Glossary geändert)
**Use-Cases**
• Alle Kleinigkeiten & Formulierungen ausgebessert
• Fehlerfälle im Scenario erstmal nicht gemacht -> noch mal Nachfragen?
**Funktionale Anforderungen**
• Alle Kleinigkeiten & Formulierungen ausgebessert
• Auditierung bzw. Synchronisationsüberwachung erstmal auskommentiert (ist ja jetzt ereignisgesteuert)
• Punkt Effizienz -> 30 Sekunden (Wenn man als Gruppe ankommt) 

**Noch zu erledigen**
• UC10 nach Kunden-Meeting fertig stellen
• Benutzerumgebung nach Kunden-Meeting fertig stellen
• Statusmeldungen an UC anhängen
