### ISSUE TITLE
Architektur-Notebook, Design korrigieren + weiterführen

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#64]
- Kommentare von Prof. Anke abarbeiten
   - Frage der "Berechtigungen und Rollenzugehörigkeiten" im Datenbankmodell
- Anpassungen vom letzten Kundenmeeting
- Systementwurf überprüfen
   - technische Randbedingungen <> organisatorische Randbedingungen
   - Qualitätsanforderungen konkretisieren
   - Aufbau Webserver
   - Welche Komponenten werden auf dem Webserver und Terminal verwendet -> Schema
      - Aufbau der Komponenten -> Interface aufbauen
      - Zuständigkeiten der Komponenten klar Trennen (bspw. Backend aufsplitten: DB-Verwaltung und REST-API)

**Comment by MaxHaufe** [comment]
# **Vorschläge für API-Requests**

## Get

* pilot/{id}
    * returns: Daten aus Tabelle `Pilot`
* pilot/{last_name}
    * returns: (Liste von) Daten aus Tabelle `Pilot`
* /sessions_active
    * returns: gerade aktive Sessions (Endzeit is NULL)
* /sessions_all
* /pilots_active
    * returns: alle nicht-deaktivierten Piloten (Daten aus Tabelle `Pilot`)
* /pilots_inactive
    * returns: alle deaktivierten Piloten (Daten aus Tabelle `Pilot`)

## Post

* enter_pilot
    * returns: (Error Code ?)
* deactivate_pilot
    * returns: (Error Code ?)
* pilot_checkout/{id}
    * Pilot mit ID 'id' abmelden
    * returns: (Error Code ?)
* pilot_checkout_all
    * alle Piloten abmelden
  * returns: (Error Code ?)


Bei manchen Sachen bin ich mir nicht zu 100% sicher ob die sinnvoll sind - wir können das ja im Meeting diskutieren.

**Comment by alexanderheiss99** [comment]
REST API – Requests:
GET Protokollzeile
GET Pilotendaten
GET Aktuelle Einstellungen
GET Letzte Aktualisierung
GET gesamtes Protokoll
GET Login Daten

SET Pilotendaten
SET Protokolleintrag

UPDATE Protokolleintrag
UPDATE Pilotendaten (Name, RFID, aktiv,…)
UPDATE Status ändern, ob Pilot gerade aktiv am Fliegen

**Comment by Lernni** [comment]
Terminal
GET:
/pilots
/sessions
/pilots?status=active   ODER   /pilots/status/active

POST:
/pilots/checkout_all
/session/start

PUT:
/session/end
/session/filterById

Webserver
GET:

/pilots
/sessions
/sessions/latest/20
/sessions/filterByTime?from=23.04.2021?to=25.04.2021
/sessions/filterById/2
/pilots?status=active   ODER   /pilots/status/active
/pilots/findById?id=2   ODER   /pilots/id/2

POST:
/pilot …
/pilots/checkout_all

PUT:
/pilot … ?status=deactive ODER ?active=false
/session …

DELETE:
/pilot

**Comment by Lernni** [comment]
- Request-API zusammenfassen

**Comment by Lernni** [comment]
- Aufbau Webserver
