### ISSUE TITLE
Fragen/Themen für nächstes Kundengespräch

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#65]
- Fragen bezüglich Datenschutz (#61)
- Zugang zum Webserver, Aufbau Webserver
- evtl. Ablauf Deployment klären
- technische Randbedingungen (Netzwerk, Speicher, Scannermodell)

**Comment by JakobLaufer** [comment]
Fragen zur Benutzerumgebung:
• Wie viele Admins gibt es ca. ?
• Wie oft kommen Neu-Anmeldungen ca. vor?
• Wie oft kommen Gäste?
Fragen zum UC10:
• Wie soll Admin ein Gast im nachinein auf Website kenntlich machen? Genaue Vorstellungen?
