### ISSUE TITLE
Systemweite Anforderungen überprüfen

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#68]
- NFAs streichen bzw. reduzieren, wenn diese nicht explizit verlangt oder notwendig
- Architekturrelevante NFAs überprüfen und neu verlinken

**Comment by Lernni** [comment]
- NFA+3 und NFA+4 entfernen und Verlinkung aus Architecture-Notebook löschen

**Comment by JakobLaufer** [comment]
Sind entfernt & Verlinkung sind gelöscht
