### ISSUE TITLE
Design Wireframes überarbeiten

### ISSUE THREAD

**Issue by alexanderheiss99** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#69]

**Comment by Lernni** [comment]
- Admins können Passwörter zurücksetzen (Mitgliederübersicht)
- Admins können bei Mitgliedererstellung wählen zwischen Admin und normalen Pilot (CheckBox)
- Personalisierter Login (Ansicht zur Registrierung)
- Flüge editieren
