### ISSUE TITLE
Fragen/Themen für nächstes Kundenmeeting

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#76]
- Flugleiterknopf?
- Welche Anforderungen gibt es an das Passwort?

**Comment by MaxHaufe** [comment]
Wenn die Pilotendaten nach 2 Jahren (vermutlich) gelöscht werden, sollen dann alle Daten, welche sich auf diesen Piloten beziehen (Gast, Flugsession) auch mit gelöscht werden?

Ich würde denken, dass das so sinnvoll ist, anstatt dann alles auf NULL zu setzen, denn dann hätte man jede Menge (sinnlose) Daten.

**Comment by Lernni** [comment]
Würde ich auch sagen. Man könnte dann sowas wie CASCADE für den DELETE Befehle einrichten, wenn es das für SQLite3 geben sollte.

**Comment by MaxHaufe** [comment]
Ja, gibt es. Ich lasse das jetzt erstmal mit 'SET NULL'  aber das kann ich nach dem Gespräch ja schnell  ändern.

**Comment by MaxHaufe** [comment]
Wir müssen noch fragen, wann wir den Knopf bekommen, den wir zur Bestimmung des Flugleiters am Terminal brauchen.
