### ISSUE TITLE
UC10 und UC08 überprüfen und korrigieren

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#81]

**Comment by Lernni** [comment]
- Piloten können das Protokoll einsehen
- Piloten können nur eigene Flugsessions bearbeiten (Gäste hinzufügen)

**Comment by JakobLaufer** [comment]
- Da es im UC08 nur um das Einsehen geht, ist der soweit ok 
- UC10 ist korrigiert
