### ISSUE TITLE
DB-Modell für Terminal erstellen

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#82]
- ohne Tabelle Gast
- ohne Spalten Nutzername, Passwort und Ist_Admin der Tabelle Pilot

**Comment by JakobLaufer** [comment]
Hatte noch eine kurze Info beim Datenbankmodell vom Terminal geschrieben:

- reicht das vom Umfang her ?
- und Synchronisation müsste ggf noch geupdatet werden?

**Comment by Lernni** [comment]
Super, ja das reicht vom Umfang her. Beim DB-Modell vom Webserver kann ein Pilot in einer Session durch die c-Beziehung aber entweder einen oder keinen Gast haben. Außerdem würde ich noch kurz mit ergänzen, dass in der Tabelle Pilot die drei Spalten Nutzername, Passwort und Ist_Admin für den Login am Webserver dazukommen.

Bei der Synchronisation hat sich eigentlich nichts geändert. Man könnte maximal ergänzen, dass der Webserver die Tabelle Gast und die Logindaten der Piloten nicht mit synchronisiert.

**Comment by JakobLaufer** [comment]
So meinte ich das mit dem "Teil einer Flugsession" aber hab es jetzt noch mal geändert &  den Rest hinzugefügt.
Und das mit der Synchronisation hab ich hinter Konfliktpotenzial gesetzt
