### ISSUE TITLE
Requests im Backend einpflegen

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#85]
- (Ping Request)
- Settings Request -> lokale Settings.json GET /settings & POST /settings
- (CSV exportieren -> Protokolldaten)
- POST /rifd -> Erstellen neuer RFID-Tags

**Comment by MaxHaufe** [comment]
sessions POST: required bei endzeit rausnehmen
