### ISSUE TITLE
Vision ergänzen

### ISSUE THREAD

**Issue by Lernni** [Lernni/E2-Anwesenheitserfassung-fuer-Modellflugplatz#9]
Neue Erkenntnisse in der Besprechung vom 17.12 mit in die Vision einbringen:

- Motivation hinter dem Projekt: Gesetzeslage, Versicherung, Nachbarn, ...
- Benutzerumgebung

**Comment by Lernni** [comment]
Nicht funktionale Anforderungen ergänzen

**Comment by Tsatsra** [comment]
Flugleiter ergänzen

**Comment by Tsatsra** [comment]
Zeiterfassung ergänzen

**Comment by Tsatsra** [comment]
Motivation ist ergänzt
Bei der Benutzerumgebung bin ich mir nicht ganz sicher was noch ergänzt/ gemacht werden soll und ebenso bei den Nicht-Funktionalen Anforderungen
